name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ "*" ]  # Run CI on all branches

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        run: terraform -chdir=infra init
      
      - name: Terraform Validate
        run: terraform -chdir=infra validate

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          pip install pytest boto3 moto[s3,translate]
      - name: Run pytest
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        run: pytest -v tests/
